spring.application.name=cheatbank-backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sql12.freesqldatabase.com:3306/sql12827450?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sql12827450}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ANBkxhvk4K}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.jwt.secret=${APP_JWT_SECRET=8bF2kQ9xLp4vNz7mRt1yUa6cWd3hJs5eKi0oPx2qMv9tYg4n}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:604800000}
app.client-url=${APP_CLIENT_URL:http://localhost:3000,http://localhost:5173,https://fullstack-cheat-bank.vercel.app}
